### ISSUE TITLE
Add more features to the CMCD 

### ISSUE THREAD

**Issue by neoharry** [jennifergalley/CodeDuplicationChecker#6]

**Comment by neoharry** [comment]
Defined By "Type" of the variable
Scope this to primitive data types such as string, int, double

**Comment by neoharry** [comment]
to be done by sachin

**Comment by Ritesh1905** [comment]
Did we fix the normalization issue? can we normalize the comparison score between 0 to 1?

**Comment by neoharry** [comment]
For normalizing, we would need to decide the max euclidean distance we allow, which is not something we can control since 2 methods could have n-variables that contributes to the diff.
Any better ideas on how to normalize this to 0-1?

**Comment by jennifergalley** [comment]
Closed by Sachin, Rishi
